version: '3.8'
services:

############################################
######Admin UI Service######################
############################################
  admin-ui:
    build: ./ui/admin-ui
    ports:
      - "5000:3500"
    environment:
    - DAPR_HTTP_PORT=3501
    networks:
      - my-network
  
  admin-ui-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
        "-app-port", "5000",
        "-app-id", "admin-ui",
        "-app-protocol", "http",
        "-dapr-http-port", "3500",
        "-components-path", "/dapr/components",
        "-config", "/dapr/config.yaml"
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - admin-ui
    network_mode: "service:admin-ui"

  

  ############################################
  ######News Manager Service##################
  ############################################
  news-manager:
    build: ./managers/news-manager
    ports:
      - "5001:3501"
    environment:
      - DAPR_HTTP_PORT=3502
    networks:
      - my-network
  
  news-manager-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
        "-app-port", "5001",
        "-app-id", "news-manager",
        "-app-protocol", "http",
        "-dapr-http-port", "3501",
        "-components-path", "/dapr/components",
        "-config", "/dapr/config.yaml"
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - news-manager
    network_mode: "service:news-manager"
  ############################################
  ######News Service##########################
  ############################################
  news-service:
    build: ./accessors/news-service
    ports:
      - "5002:3502"
    environment:
      - DAPR_HTTP_PORT=3501
    env_file:
      - .env
    networks:
      - my-network
  
  news-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
        "-app-port", "5002",
        "-app-id", "news-service",
        "-app-protocol", "http",
        "-dapr-http-port", "3502",
        "-components-path", "/dapr/components",
        "-config", "/dapr/config.yaml"
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - news-service
    network_mode: "service:news-service"

  ################################################
  ######customer UI Service#######################
  ################################################
  customer-ui:
    build: ./ui/customer-ui
    ports:
      - "5003:3503"
    environment:
    - DAPR_HTTP_PORT=3504
    networks:
      - my-network
  customer-ui-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
        "-app-port", "5003",
        "-app-id", "customer-ui",
        "-app-protocol", "http",
        "-dapr-http-port", "3503",
        "-components-path", "/dapr/components",
        "-config", "/dapr/config.yaml"
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - customer-ui
    network_mode: "service:customer-ui"

  ################################################
  ######customer Service##########################
  ################################################
  customer-service:
    build: ./customer/customer-service
    ports:
      - "5004:3504"
    environment:
      - DAPR_HTTP_PORT=3505
    env_file:
      - .env
    networks:
      - my-network
  customer-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
        "-app-port", "5004",
        "-app-id", "customer-service",
        "-app-protocol", "http",
        "-dapr-http-port", "3504",
        "-components-path", "/dapr/components",
        "-config", "/dapr/config.yaml"
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - customer-service
    network_mode: "service:customer-service"
  ################################################
  ######User Manager Service#####################
  ################################################
  user-manager:
    build: ./managers/user-manager
    ports:
      - "5005:3505"
    environment:
      - DAPR_HTTP_PORT=3506
    networks:
      - my-network
  user-manager-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
        "-app-port", "5005",
        "-app-id", "user-manager",
        "-app-protocol", "http",
        "-dapr-http-port", "3505",
        "-components-path", "/dapr/components",
        "-config", "/dapr/config.yaml"
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - user-manager
    network_mode: "service:user-manager"
  ################################################
  ######User Service##############################
  ################################################
  user-service:
    build: ./accessors/user-service
    ports:
      - "5006:3506"
    environment:
      - DAPR_HTTP_PORT=3507
    env_file:
      - .env
    networks:
      - my-network
  user-service-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
        "-app-port", "5006",
        "-app-id", "user-service",
        "-app-protocol", "http",
        "-dapr-http-port", "3506",
        "-components-path", "/dapr/components",
        "-config", "/dapr/config.yaml"
        ]
    volumes:
      - "./dapr/:/dapr"
    depends_on:
      - user-service
    network_mode: "service:user-service"

  ################################################
  ######MongoDB Service###########################
  ################################################
  mongo:
    image: "mongo:4.4"
    volumes:
      - "./mongo-data:/data/db"
    env_file:
      - .env
    networks:
      - my-network
  

networks:
  my-network:
    driver: bridge
